CREATE TABLE Movie (
    MOVIE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RELEASE_YEAR INT,
    TITLE VARCHAR(255),
    STUDIOS VARCHAR(255),
    PRODUCERS VARCHAR(255),
    WINNER BOOLEAN
);

CREATE SEQUENCE MOVIE_SEQ START WITH 1 INCREMENT BY 1;